// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD95u9kINwkI4hT6Hamx0tOSm6k-s3mogg',
    appId: '1:302556638942:web:acedab8a4a522580d45c4f',
    messagingSenderId: '302556638942',
    projectId: 'vote-app-15172',
    authDomain: 'vote-app-15172.firebaseapp.com',
    storageBucket: 'vote-app-15172.appspot.com',
    measurementId: 'G-FE5WW6Q53R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzUULNPbNhTtglplFrI_pw3EG6pVmAdkQ',
    appId: '1:302556638942:android:f102de028f3621b6d45c4f',
    messagingSenderId: '302556638942',
    projectId: 'vote-app-15172',
    storageBucket: 'vote-app-15172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOOxjQanORXmuyBAMTV9AHjmmacSMzKBo',
    appId: '1:302556638942:ios:6e9a9081fa5514c3d45c4f',
    messagingSenderId: '302556638942',
    projectId: 'vote-app-15172',
    storageBucket: 'vote-app-15172.appspot.com',
    iosClientId: '302556638942-q3r9hks79dbnj0nv8k8c8q8upnsr5haa.apps.googleusercontent.com',
    iosBundleId: 'com.example.voteApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOOxjQanORXmuyBAMTV9AHjmmacSMzKBo',
    appId: '1:302556638942:ios:6e9a9081fa5514c3d45c4f',
    messagingSenderId: '302556638942',
    projectId: 'vote-app-15172',
    storageBucket: 'vote-app-15172.appspot.com',
    iosClientId: '302556638942-q3r9hks79dbnj0nv8k8c8q8upnsr5haa.apps.googleusercontent.com',
    iosBundleId: 'com.example.voteApplication',
  );
}
